### ISSUE TITLE
Test name explorer 1.0-SNAPSHOT 

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/name-explorer-plugin#1]
Tested on 12-13 Nov
URL: https://bie-test.ala.org.au/nameExplorer
_ | _
-- | --
Git commit date/time | 2019-10-18T14:54:04+1100
bead1d67c77020d7080b860d3069c2c98f5674fb | bead1d6
develop | develop

**Comment by javier-molina** [comment]
Test plan
https://confluence.csiro.au/display/ALASD/Name+Index+Explorer+Test+Plan

Findings:

Scientific Name should be marked as mandatory (probably the * convention).

A message should be displayed to explicitly say when a search didn't produce any results.

**Comment by charvolant** [comment]
Fixes in https://github.com/AtlasOfLivingAustralia/name-explorer-plugin/pull/2 on develop branch
